apiVersion: v1
kind: Secret

metadata:
  name: db-connection

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19KUGp6NkoyZlNOYTBydGxLQnlNQHBhc3MtaW4tZG8tdXNlci0xNjIyNzA0OC0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL3Bhc3MtaW4/c3NsbW9kZT1yZXF1aXJlCg==
