apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: arthurpmachadodev/nlw.service.passin:cd23a39
        env:
        - name: DATABASE_URL
          value: "postgresql://doadmin:AVNS_JPjz6J2fSNa0rtlKByM@pass-in-do-user-16227048-0.c.db.ondigitalocean.com:25060/pass-in?sslmode=require"
        - name: API_BASE_URL
          value: "http://localhost:3333"
        ports:
        - containerPort: 3333
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
